app:
  datasource:
#      If you want to use PostgreSQL, uncomment the line below and comment out line 5.
#      jdbc-url: jdbc:postgresql://localhost:5432/ctfdb
      jdbc-url: jdbc:h2:mem:ctfh2db
      username: dbadmin
      password:
      pool-size: 30

#spring:
#  datasource:
#    hikari:
#      jdbc-url: jdbc:postgresql://localhost:5432/ctfdb
#    driver-class-name: org.postgresql.Driver
#    username: postgres
#    password: 12345678